cache: bundler
language: ruby
rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.5
  - 2.7.0
  - jruby-9.2.7.0
gemfile:
  - gemfiles/Gemfile.rails-5-0-stable
  - gemfiles/Gemfile.rails-5-1-stable
  - gemfiles/Gemfile.rails-5-2-stable
  - Gemfile
matrix:
  exclude:
    - rvm: 2.3.8
      gemfile: Gemfile
    - rvm: 2.4.6
      gemfile: Gemfile
    - rvm: jruby-9.1.17.0
      gemfile: Gemfile
  allow_failures:
    - rvm: jruby-9.1.17.0
      gemfile: Gemfile
    - rvm: jruby-9.2.7.0
      gemfile: Gemfile
before_install:
  - gem update --system
notifications:
  email: true
script: "bin/test"
